const myData = [
  {
    id: 1,
    name: "Brad Traversy",
    skills: "Full Stack Web Developer",
    country: "United States",
    salary: 200000,
    img: "https://res.cloudinary.com/abidazad/image/upload/v1632631652/Brad_Traversy_x2ok5r.jpg",
  },
  {
    id: 2,
    name: "Ben Awad",
    skills: "software Engineer",
    country: "United States",
    salary: 100000,
    img: "https://res.cloudinary.com/abidazad/image/upload/v1632631652/Ben_Awad_i3ovbf.jpg",
  },
  {
    id: 3,
    name: "Web Dev Simplified",
    skills: "Full Stack Web Developer",
    country: "United States",
    salary: 400000,
    img: "https://res.cloudinary.com/abidazad/image/upload/v1632631652/Web_Dev_Simplified_ieomlf.png",
  },
  {
    id: 4,
    name: "JavaScript Mastery",
    skills: "Full Stack Web Developer",
    country: "United States",
    salary: 200000,
    img: "https://res.cloudinary.com/abidazad/image/upload/v1632631652/download_1_armdec.png",
  },
  {
    id: 5,
    name: "Code With Harry",
    skills: "Full Stack Web Developer",
    country: "India",
    salary: 200000,
    img: "https://res.cloudinary.com/abidazad/image/upload/v1632631791/code-with-harry_xwvpmh.jpg",
  },
  {
    id: 6,
    name: "Dev Ed",
    skills: "Full Stack Web Developer",
    country: "United States",
    salary: 200000,
    img: "https://res.cloudinary.com/abidazad/image/upload/v1632631652/Dev_Ed_gl5ydd.jpg",
  },
  {
    id: 7,
    name: "Free Code Camp",
    skills: "Full Stack Web Developer",
    country: "United States",
    salary: 200000,
    img: "https://res.cloudinary.com/abidazad/image/upload/v1632631652/Free_Code_Camp_etshz6.png",
  },
  {
    id: 8,
    name: "Mosh",
    skills: "Full Stack Web Developer",
    country: "United States",
    salary: 300000,
    img: "https://res.cloudinary.com/abidazad/image/upload/v1632665284/Mosh_nhugo5.jpg",
  },
  {
    id: 9,
    name: "The Net Ninja",
    skills: "Full Stack Web Developer",
    country: "United States",
    salary: 200000,
    img: "https://res.cloudinary.com/abidazad/image/upload/v1632631652/download_2_yfqvoo.png",
  },
  {
    id: 10,
    name: "codeSTACKr",
    skills: "Full Stack Web Developer",
    country: "United States",
    salary: 200000,
    img: "https://res.cloudinary.com/abidazad/image/upload/v1632665284/codeSTACKr_lqd6g3.png",
  },
  {
    id: 11,
    name: "lama Dev",
    skills: "Full Stack Web Developer",
    country: "United States",
    salary: 200000,
    img: "https://res.cloudinary.com/abidazad/image/upload/v1632665284/lama_bkoybk.jpg",
  },
  {
    id: 12,
    name: "Coder Coder ",
    skills: "Full Stack Web Developer",
    country: "United States",
    salary: 300000,
    img: "https://res.cloudinary.com/abidazad/image/upload/v1632665284/Coder_Coder_ny5vjs.jpg",
  },
  {
    id: 13,
    name: "Program With Erik",
    skills: "Full Stack Web Developer",
    country: "United States",
    salary: 80000,
    img: "https://res.cloudinary.com/abidazad/image/upload/v1632665284/Program_With_Erik_fskdd7.jpg",
  },
  {
    id: 14,
    name: "WEB CIFAR",
    skills: "Full Stack Web Developer",
    country: "United States",
    salary: 200000,
    img: "https://res.cloudinary.com/abidazad/image/upload/v1632665285/WEB_CIFAR_bh2vfs.png",
  },
  {
    id: 15,
    name: "Coding Garden",
    skills: "Full Stack Web Developer",
    country: "United States",
    salary: 200000,
    img: "https://res.cloudinary.com/abidazad/image/upload/v1632665285/Coding_Garden_kxro5i.png",
  },
];

export default myData;
